import '../models/movie_item.dart';

List<MovieItem> SAMPLE_MOVIES = [
  MovieItem(
      id: '2333',
      title: 'Doctor Strange : MOM',
      description:
          'Dr Stephen Strange casts a forbidden spell that opens a portal to the multiverse. However, a threat emerges that may be too big for his team to handle.',
      imagePath: 'assets/images/samples/sample_movie2.png',
      ratingInStars: 4,
      genre: 'Action/Adventure',
      director: 'Sam Raimi',
      length: '2hr 6mins',
      trailerUrl: 'https://www.youtube.com/watch?v=aWzlQ2N6qqg'),
  MovieItem(
      id: '23f3',
      title: 'KFG 2',
      description: '',
      imagePath: 'assets/images/samples/sample_movie1.png',
      ratingInStars: 5,
      genre: 'Action/Crime/Drama/History',
      director: 'Prashanth Neel',
      length: '2hr 6mins',
      trailerUrl: 'https://www.youtube.com/watch?v=JKa05nyUmuQ'),
  MovieItem(
      id: '2fd33',
      title: 'RRR',
      description: '',
      imagePath: 'assets/images/samples/sample_movie3.png',
      ratingInStars: 3,
      genre: 'Action/Crime/Drama/History',
      director: 'SS Rajmoli',
      length: '2hr 26mins',
      trailerUrl: 'https://www.youtube.com/watch?v=xo1P2sQdhC0'),
  MovieItem(
      id: '232d3',
      title: 'Doctor Strange : MOM',
      description:
          'Dr Stephen Strange casts a forbidden spell that opens a portal to the multiverse. However, a threat emerges that may be too big for his team to handle.',
      imagePath: 'assets/images/samples/sample_movie2.png',
      ratingInStars: 4,
      genre: 'Action/Adventure',
      director: 'Sam Raimi',
      length: '2hr 6mins',
      trailerUrl: 'https://www.youtube.com/watch?v=aWzlQ2N6qqg'),
  MovieItem(
      id: '2ds32d',
      title: 'KFG 2',
      description: '',
      imagePath: 'assets/images/samples/sample_movie1.png',
      ratingInStars: 5,
      genre: 'Action/Crime/Drama/History',
      director: 'Prashanth Neel',
      length: '2hr 6mins',
      trailerUrl: 'https://www.youtube.com/watch?v=JKa05nyUmuQ'),
  MovieItem(
      id: '86g53',
      title: 'RRR',
      description: '',
      imagePath: 'assets/images/samples/sample_movie3.png',
      ratingInStars: 3,
      genre: 'Action/Crime/Drama/History',
      director: 'SS Rajmoli',
      length: '2hr 26mins',
      trailerUrl: 'https://www.youtube.com/watch?v=xo1P2sQdhC0'),
];

List<MovieItem> UPCOMING_MOVIES = [
  MovieItem(
    id: 'as33',
    title: 'Thor: Love And Thunder',
    description: '',
    imagePath: 'assets/images/upcoming_movies/sample_upcoming_movie2.png',
    ratingInStars: 5,
    genre: 'Action/Adventure/Fiction/Mystery',
    director: 'Sam Raimi',
    length: '2hr 12mins',
    trailerUrl: '',
    releaseDate: '11-July-22',
  ),
  MovieItem(
    id: 'er3d3',
    title: 'Pathan',
    description: '',
    imagePath: 'assets/images/upcoming_movies/sample_upcoming_movie1.png',
    ratingInStars: 4,
    genre: 'Action/Crime',
    director: 'Prashanth Neel',
    length: '1hr 40mins',
    trailerUrl: '',
    releaseDate: '3-Aug-22',
  ),
  MovieItem(
    id: 'as354',
    title: 'Thor: Love And Thunder',
    description: '',
    imagePath: 'assets/images/upcoming_movies/sample_upcoming_movie2.png',
    ratingInStars: 5,
    genre: 'Action/Adventure/Fiction/Mystery',
    director: 'Sam Raimi',
    length: '2hr 12mins',
    trailerUrl: '',
    releaseDate: '11-July-22',
  ),
  MovieItem(
    id: 'er3f4d3',
    title: 'Pathan',
    description: '',
    imagePath: 'assets/images/upcoming_movies/sample_upcoming_movie1.png',
    ratingInStars: 4,
    genre: 'Action/Crime',
    director: 'Prashanth Neel',
    length: '1hr 40mins',
    trailerUrl: '',
    releaseDate: '3-Aug-22',
  ),
];
